tasks/main.yml

There are 3 proposed changes here:
1. Only install system or user rbenv, i.e. don't install the system rbenv when you've selected the 'user' mode.
1. Don't install the rbenv.sh on OpenBSD--it won't work because OpenBSD doesn't use profile.d. For now one must manually add the rbinit stuff to your shell config *before* using the rbenv role to setup rbenv for a user, or it will break. That is to say, its slightly less broken, but not yet a great solution.
1. Use the user's chosen shell when running rbenv, so for example in my case using zsh, the ruby installation tasks will work.

only install system or user rbenv, not both

---

tasks/main.yml

Fixes regression introduced in #20
System rbenv wasn’t installing Ruby when version not found. More on
https://github.com/zzet/ansible-rbenv-role/pull/20#commitcomment-9223104
I've tested this successfully, locally.

Fixes system rbenv ruby install

---

defaults/main.yml
tasks/yum_build_depends.yml

ruby 2.2.0 released and ruby-build had release v20141225.
This pr updated ruby-build to newest version and user can install ruby 2.2.0.

update ruby-build to v20141225 which ruby-2.2.0 stable included

---

README.md
tasks/main.yml

Based on my own incapacity of reading the README (#24) I thought we could simplify the interface for the `rbenv_users` variable. Instead of a hash with the user information including home, use ~ to figure it out. I was trying to use $HOME, but came across http://stackoverflow.com/questions/22873409/ansible-sudo-user-not-using-the-correct-home-directory, long story short, ~ seems to do the trick just fine.
`{{ item[1].home }}/.rbenv`, or `{{ rbenv_root }}` as I prefer to call it, was created when each user cloned the repo, so there is no need to chown it. Also user and group name might be different.
Here is the configuration and output for a local run with two users:
```yaml
- role: ../ansible-rbenv-role
rbenv:
env: user
version: v0.4.0
ruby_version: 2.1.5
rbenv_users:
- deploy
- vagrant …
```

Simplify rbenv_users interface: Username only

---

tasks/main.yml

A couple of the tasks had duplicate names, and didn't accurately describe what they were doing. Hopefully this makes it a bit clearer what is actually being done within said tasks.

Fix duplicate task names

---

tasks/apt_build_depends.yml

In Ruby 2.2.0 depends on `libffi`.
But not include this on apt environment.

Add libffi-dev on apt environment for ruby 2.2.0

---

tasks/main.yml

Hi, this fixes a crash when executing this role in check mode:
```
TASK: [rbenv | install ruby {{ rbenv.ruby_version }} for select users] ********
fatal: [...] => error while evaluating conditional: (not "system" == "user") and (item[0].rc != 0)
FATAL: all hosts have already failed -- aborting
```
This fails because the previous task `check ruby {{ rbenv.ruby_version }} installed for select users` was skipped, which means there is no value for item[0].rc in the task that fails.
Thank you veru much for this role, it's been immensely useful to us.

Don't skip ruby version checking in check mode

---

tasks/main.yml

Ansible 1.9 ( https://github.com/ansible/ansible/blob/devel/CHANGELOG.md#19-dancing-in-the-street---mar-25-2015 ) changed  'force' flag for source control modules from 'true' to 'false' by default. This commit restores previous behavior and force check-out rbenv repo and plugins.

Git should use 'force' flag set to true to override local changes in rbenv or plugins repos

---

tasks/main.yml

The new check if the desired Ruby version is selected ensures that the version is set even if it is installed already.

Check ruby version selected

---

README.md
defaults/main.yml

rbenv is now its own org on github (with several plugins being part thereof). this patch updates the repo url (a redirect occurs, though) and ruby-build to v20151230.

ruby-build v20151230 (ruby 2.3.0)

---

.kitchen.yml
tasks/apt_build_depends.yml
tasks/main.yml
tasks/yum_build_depends.yml

Replace deprecated sudo and sudo_user calls with become and become_user (simple search and replace) to kill deprecation warnings in ansible >2.0

replace sudo and sudo_user with become and become_user

---

files/gemrc

--rdoc and --ri deprecated option from 2.x
(But under 1.9.x versions uses only --rdoc and --ri.)
http://guides.rubygems.org/command-reference/#gem-install
https://github.com/rubygems/rubygems/commit/0d22d602
In accordance with the current situation, I modified that.

modify gemrc to replace --rdoc and --ri.

---

tasks/main.yml

Switched the "with:" and "with_together:" syntax to using the "{{ }}" syntax.  Ansible 2.0 complains about the undecorated syntax.  Understandable if you don't want to switch, it's not scheduled for removal until Ansible 2.3, and I don't know what the minimum required is.

Use "{{ }}" syntax for with and with_together, fixes deprecation warnings

---

tasks/main.yml

I ran into trouble with system-wide installs, as my user did not have permissions to checkout into /usr/local. I believe that the current tests don't catch this because the user is set to root in [site.yml](https://github.com/zzet/ansible-rbenv-role/blob/master/test/integration/site.yml#L5), while I use a non-root user to login and `become` only when needed.
I haven't run the tests yet, because I lack the time to set up serverspec, but this pull request fixes the issue for me.
Edit: I believe this is #38.

fixes permission error when installing rbenv system-wide

---

.travis.yml

The build is currently broken, because travis apparently doesn't support python on OS x (although I'm surprised the travis script ever worked, since it relies on `apt-get`.

Fix the currently broken built (Travis doesn't support python on OS X)

---

README.md
tasks/main.yml

* Allow for a group of users to share a single system install and still facilitate the usual rbenv workflows.

Enable system install with delegatable ownership of rbenv_root

---

tasks/main.yml

Ran into this when provisioning my Macbook. I don't believe there's a `/etc/profile.d` either. Should suffice since you're generally gonna want rbenv installed as a user anyway.

Darwin doesn't have a root group either.

---

README.md
tasks/main.yml

Had an issue with a couple of servers where default `TMPDIR` was mounted as a `noexec` mount and because there's no good way of passing env variables into roles, here's a change that will allow for that. `rbenv_tmpdir` will only be used when installing rubies.

Allow for a configurable TMPDIR when installing rubies

---

meta/main.yml
tasks/dnf_build_depends.yml
tasks/main.yml

Hey,
I'm using Fedora as my development box on Vagrant and I got a problem with installing ruby with this role: on latest Fedora version DNF installed as default package manager so `ansible_pkg_mgr ` returns `'dnf'` instead of `'yum'`.  I've added the task to install dependencies via DNF. 
Please let me know if something wrong with this PR.
Thanks.

Add dnf support to install dependencies

---

tasks/apt_build_depends.yml

concept borrowed from other popular roles such as
https://github.com/geerlingguy/ansible-role-nginx/blob/master/tasks/setup-Debian.yml

make debian apt cache update idempotent and valid for a minimum period

---

README.md
defaults/main.yml

The ruby-build plugin updates very regularly with new ruby versions.
The plugin itself appears to expect that master branch is used; for example, the instructions that it issues if an attempt is made to install a missing version are
https://github.com/rbenv/ruby-build/blob/d6641376641b3a54aab7a02e1d81b26e95e16bb5/bin/rbenv-install#L218
```
cd ~/.rbenv/plugins/ruby-build && git pull && cd -
```
which doesn't work if we pin to a release version.
In my experience releases are backwards compatible so there seems little point to avoid using master.

use master branch for ruby-build plugin

---

tasks/main.yml
tasks/system_install.yml
tasks/user_install.yml

The tmpdir presence task creates ~/.rbenv, which prevents subsequent tasks from cloning to ~/.rbenv. If it's simply removed, the cloning task works fine. As well, since the shell is not refreshed between tasks, ansible can't find the rbenv bin without an explicit path.

Fix OSX user install

---

tasks/main.yml
tasks/system_install.yml

As per discussion on https://github.com/zzet/ansible-rbenv-role/pull/74#issuecomment-266468021
The idea of this variable was to use the remote env var but lookup actually pulls from the Ansible control machine. This fixes that and uses the same default as the upstream ruby-build process
https://github.com/rbenv/ruby-build/blob/master/bin/ruby-build#L1211

Fix usage of tmp dir

---

tasks/apt_build_depends.yml
tasks/dnf_build_depends.yml
tasks/main.yml
tasks/system_install.yml
tasks/user_install.yml
tasks/yum_build_depends.yml

A single tag does not allow segregation of tasks. In fact if this tag is currently used, it breaks the role as it is not applied to all actions.
Removing tags was an alternative approach suggested to the outstanding PR https://github.com/zzet/ansible-rbenv-role/pull/78

remove inconsistently used tags

---

meta/main.yml

If you are running ansible version prior to 2.2.0 you cannot use the check mode.

pump min ansible version to 2.2.0

---

tasks/apt_build_depends.yml

For those poor souls who still have to use Ruby 1.8. Tested against a vanilla Ubuntu 14.04 install.

Install support packages for Ruby 1.8.7 on Debian based OS

---

tasks/yum_build_depends.yml

DigitalOcean droplets running CentOS do not, by default.

ensure bzip is installed on RHEL/CentOS

---

README.md
defaults/main.yml
tasks/apt_build_depends.yml
tasks/dnf_build_depends.yml
tasks/yum_build_depends.yml

Some ruby compilation flags may require extra dependencies to be installed on the machines.
For example, `--with-jmalloc` requires `libjemalloc-dev` to be installed on Debian, otherwise ruby compilation fails.
This PR adds a feature to install the required system packages before compiling rubies.

Add an option to install extra packages before building ruby

---

README.md
defaults/main.yml
tasks/system_install.yml
tasks/user_install.yml

Please merge the rbenv versions PR before this one.
Compares the installed rubies list with the `rbenv.rubies` variable to decide which rubies are not wanted at the target system anymore.
All ruby versions not listed in `rbenv.rubies` will be removed.

Clean up old rubies

---

tasks/user_install.yml

The conditional is not correct. If you keep the last `[0]` it returns the first character of the `item[0].item`.
And of course the conditional is never met and so the ruby is never installed.

Fixes #102: conditional arg item[0] turn into item.

---

defaults/main.yml
tasks/apt_build_depends.yml
tasks/dnf_build_depends.yml
tasks/yum_build_depends.yml

My use case is to install a Ruby 2.3.3 on a debian.
As you can read in the link below, I do not need the package `libssl-dev` (which is now in version 1.1) but the previous `libssl1.0-dev`. And your role install the lastest version (Cf. [line 14](https://github.com/zzet/ansible-rbenv-role/blob/master/tasks/apt_build_depends.yml#L14)).
I know that you propose a `rbenv_extra_depends` but this is an addition and not a modification of the packages to install.
In order to be able to tweak the prequisite packages I suggest to proceed with default variables. One variable per package manager.
This feature is an answer to my use case, but can be useful to other situation.
Source : https://github.com/rbenv/ruby-build/issues/1048#issuecomment-275152741

Creation of Prerequisite Packages variables

---

tasks/apt_build_depends.yml

In order to improve the use case of the ruby 1.8.7, I propose this PR.
The benefits are :
1. Remove an ignore_errors
2. Remove a non-recommended `shell`
3. Improve idempotence

Ruby 1.8.7 case improvement.

---

tasks/system_install.yml
tasks/user_install.yml

When the vars for multiple Rubies are specified,
(e.g.
```
rbenv:
rubies:
- version: 2.3.5
- version: 2.4.2
```
The installation is failed with the following message:
```
skipping: [web] => (item=[{'_ansible_parsed': True, 'stderr_lines': [u'/bin/sh: 1: -lc: not found'], '_ansible_item_result': True, u'end': u'2017-10-04 01:09:22.817320', '_ansible_no_log': False, u'stdout': u'', u'cmd': u'$SHELL -lc "rbenv versions --bare"', u'msg': u'non-zero return code', u'rc': 127, u'start': u'2017-10-04 01:09:22.662029', u'delta': u'0:00:00.155291', 'item': u'rbenv.rubies', u'changed': False, u'invocation': {u'module_args': {u'creates': None, u'executable': None, u'_uses_shell': True, u'_raw_params': u'$SHELL -lc "rbenv versions --bare"', u'removes': None, u'warn': True, u'chdir': None, u'stdin': …
```

Fix for multiple Rubies installation

---

defaults/main.yml
tasks/user_install.yml

I would like to use the rbenv role on systems without having to change anything outside the scope of user. This change allows the ability to disable the configuration of rbenv profile snippets. The default behaviour remains unchanged.

Optionally do not install profile snippet for users

---

tasks/apt_build_depends.yml
tasks/dnf_build_depends.yml
tasks/yum_build_depends.yml

`extra_build_depends` variable was apparently broken, the corresponding task was never executed.
This PR fixes the behaviour, allowing to install ruby with jemalloc.

Harmonize syntax for extra_build_depends variable iteration

---

README.md

It's `rbenv_extra_depends`, not `rbenv.rbenv_extra_depends`.
Cheers!

README: Fix indentation of rbenv_extra_depends

---

meta/main.yml

Required for `import_tasks`: https://docs.ansible.com/ansible/2.4/import_tasks_module.html

meta: bump minimum version to 2.4

---

tasks/apt_build_depends.yml
tasks/dnf_build_depends.yml
tasks/homebrew_build_depends.yml
tasks/yum_build_depends.yml

Correct syntax for squash_actions deprecation warnings:
> [DEPRECATION WARNING]: Invoking "homebrew" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `name: "{{ item }}"`, please use `name: ['openssl', 'libyaml']` and remove the loop. This feature will be removed in version 2.11.

Fix 2.11 deprecation warnings

---

tasks/system_install.yml
tasks/user_install.yml

2.12 changes bare variable interpretation in conditionals. Ensure rbenv_clean_up is always treated as bool. Part of https://github.com/ansible/ansible/issues/53428

Deprecation warnings on bare variable interpretation

---

tasks/system_install.yml

This is the only tasks explicitly using bash rather than $SHELL. With this out of the way bash is not needed and any other shell can do the job properly.

Remove dependency on bash

---

defaults/main.yml

The [rbenv/rbenv-installer](https://github.com/rbenv/rbenv-installer) project has renamed the primary branch to `main`.
Updating the branch name here will ensure that builds continue to work.
Closes #147

Update rbenv-installer branch name to match source repo

---

tasks/user_install.yml

Resolves issue where setting the default Ruby version for users was failing with an error like below.
```
TASK [zzet.rbenv : set ruby 2.5.6 for select users] ********************************************************************************************************************************
failed: [neptune] (item=[{'changed': False, 'end': '2019-09-12 23:10:16.341792', 'stdout': '', 'cmd': '$0 -lc "~/.rbenv/bin/rbenv version | cut -d \' \' -f 1 | grep -Fx \'2.5.6\'"', 'failed': False, 'delta': '0:00:00.036825', 'stderr': '', 'rc': 1, 'invocation': {'module_args': {'creates': None, 'executable': None, '_uses_shell': True, 'strip_empty_ends': True, '_raw_params': '$0 -lc "~/.rbenv/bin/rbenv version | cut -d \' \' -f 1 | grep -Fx \'2.5.6\'"', 'removes': None, 'argv': None, 'warn': True, 'chdir': …
```

Using fully qualified path to rbenv for user install
